/** @format */

let c_data = [
  {
    id: 1,
    username: "sunny_girl",
    age: 28,
    place: "Miami",
    description:
      "Will I get to the University admission for my desired Graduate Program?",
    verdict: "Yes, it is on your way",
    amount: 20,
  },
  {
    id: 2,
    username: "harryboy",
    age: 33,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 3,
    username: "redhair",
    age: 51,
    place: "Los Angeles",
    description: "Will I re-marry and will it do good for me?",
    verdict: "Yes you can, but do it end of the year and you will be happy",
    amount: 32,
  },
  {
    id: 4,
    username: "harryboy",
    age: 1,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 5,
    username: "harryboy",
    age: 2,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 6,
    username: "harryboy",
    age: 3,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 7,
    username: "harryboy",
    age: 4,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 8,
    username: "harryboy",
    age: 5,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 9,
    username: "harryboy",
    age: 6,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 10,
    username: "harryboy",
    age: 7,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 11,
    username: "harryboy",
    age: 8,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 12,
    username: "harryboy",
    age: 9,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 13,
    username: "harryboy",
    age: 10,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
  {
    id: 14,
    username: "harryboy",
    age: 11,
    place: "Dubai",
    description: "Will I marry soon with my gf?",
    verdict: "It will take about 6 months",
    amount: 10,
  },
];
export { c_data };
